### ISSUE TITLE
Attribute matching doesn't handle arrays

### ISSUE THREAD

**Issue by gareth-robinson** [goofballLogic/ld-query#12]
I've noticed that attributes can be arrays e.g.

```
"@type": [
    "http://www.example.org#deleteOperation",
    "http://www.w3.org/ns/hydra/core#DeleteResourceOperation"
]
```

The current matching does not handle this.

**Comment by gareth-robinson** [comment]
I've created pull request https://github.com/goofballLogic/ld-query/pull/11 as a fix for this.

**Comment by goofballLogic** [comment]
I note that this is just for special cases - @type may be the only one.
Normal properties can't have arrays - they would just turn into multi-valued properties http://tinyurl.com/zea4ysw

**Comment by gareth-robinson** [comment]
Covered as part of changes already committed
