### ISSUE TITLE
Attribute selector bug - must be adjacent to attributed node

### ISSUE THREAD

**Issue by goofballLogic** [goofballLogic/ld-query#17]
`
ex:node [@index=1234]
`
( select the descendent of ex:node with an @index of 1234 )

is incorrectly interpreted as:

`
ex:node[@index=1234]
`
( select the ex:node with an @index of 1234 )

**Comment by gareth-robinson** [comment]
Does that mean the examples in README.md and the majority of tests in selection-by-multiple-attributes.feature are incorrectly defined?

**Comment by gareth-robinson** [comment]
Never mind, I see the difference now!

I've submitted pull request https://github.com/goofballLogic/ld-query/pull/19

**Comment by goofballLogic** [comment]
This was closed by pull request #19
