### ISSUE TITLE
Should @type be "final"

### ISSUE THREAD

**Issue by comopra** [goofballLogic/ld-query#21]
Currently, if you query for @id, @value or @index, you get the literal value back, rather than a QueryNode(s). Currently querying for @type returns QueryNode  - shouldn't it also return the value instead? If there's more than one @type, an array of the literal values could be returned.

**Comment by goofballLogic** [comment]
Hmm. Probably would work. What do you think @gareth-robinson ?

**Comment by gareth-robinson** [comment]
Yes, that would seem to be the behaviour we should expect.

**Comment by goofballLogic** [comment]
@gareth-robinson could you check this commit for me?

**Comment by gareth-robinson** [comment]
Yep, looks fine
